//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Dofus_1._29._1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot_Dofus_1._29._1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100 {
            get {
                object obj = ResourceManager.GetObject("_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("_101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _110 {
            get {
                object obj = ResourceManager.GetObject("_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _111 {
            get {
                object obj = ResourceManager.GetObject("_111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _120 {
            get {
                object obj = ResourceManager.GetObject("_120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _121 {
            get {
                object obj = ResourceManager.GetObject("_121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50 {
            get {
                object obj = ResourceManager.GetObject("_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51 {
            get {
                object obj = ResourceManager.GetObject("_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60 {
            get {
                object obj = ResourceManager.GetObject("_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61 {
            get {
                object obj = ResourceManager.GetObject("_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _70 {
            get {
                object obj = ResourceManager.GetObject("_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71 {
            get {
                object obj = ResourceManager.GetObject("_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80 {
            get {
                object obj = ResourceManager.GetObject("_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81 {
            get {
                object obj = ResourceManager.GetObject("_81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90 {
            get {
                object obj = ResourceManager.GetObject("_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _91 {
            get {
                object obj = ResourceManager.GetObject("_91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agilidad {
            get {
                object obj = ResourceManager.GetObject("agilidad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar_cuenta {
            get {
                object obj = ResourceManager.GetObject("agregar_cuenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alcanze {
            get {
                object obj = ResourceManager.GetObject("alcanze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function delay(ms)
        ///	delayFuncion(ms)
        ///	coroutine.yield()
        ///end
        ///
        ///mapa =
        ///{
        ///	enCelda = api.mapa.enCelda,
        ///	enMapa = api.mapa.enMapa,
        ///	actualMapa = api.mapa.actualMapa,
        ///	actualPosicion = api.mapa.actualPosicion,
        ///
        ///	moverCelda = function(celda_id)
        ///		if api.mapa.moverCelda(celda_id) then
        ///			coroutine.yield()
        ///		end
        ///	end,
        ///
        ///	cambiarMapa = function(posicion)
        ///		if api.mapa.cambiarMapa(posicion) then
        ///			coroutine.yield()
        ///		end
        ///	end
        ///}
        ///
        ///npc =
        ///{
        ///	npcBanco = function(npc_id)
        ///		if api.npc.npcBanco(npc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string api_ayuda {
            get {
                return ResourceManager.GetString("api_ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balanza {
            get {
                object obj = ResourceManager.GetObject("balanza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boton_ajustes {
            get {
                object obj = ResourceManager.GetObject("boton_ajustes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boton_conectar {
            get {
                object obj = ResourceManager.GetObject("boton_conectar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boton_mas {
            get {
                object obj = ResourceManager.GetObject("boton_mas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boton_play {
            get {
                object obj = ResourceManager.GetObject("boton_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boton_stop {
            get {
                object obj = ResourceManager.GetObject("boton_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_naranja {
            get {
                object obj = ResourceManager.GetObject("circulo_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_rojo {
            get {
                object obj = ResourceManager.GetObject("circulo_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_verde {
            get {
                object obj = ResourceManager.GetObject("circulo_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corazon {
            get {
                object obj = ResourceManager.GetObject("corazon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cruz_roja {
            get {
                object obj = ResourceManager.GetObject("cruz_roja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cruz_roja_pequeña {
            get {
                object obj = ResourceManager.GetObject("cruz_roja_pequeña", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dinero_kamas {
            get {
                object obj = ResourceManager.GetObject("dinero_kamas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documento_azul {
            get {
                object obj = ResourceManager.GetObject("documento_azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap energia {
            get {
                object obj = ResourceManager.GetObject("energia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap experiencia {
            get {
                object obj = ResourceManager.GetObject("experiencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_direccion_izquierda {
            get {
                object obj = ResourceManager.GetObject("flecha_direccion_izquierda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuerza {
            get {
                object obj = ResourceManager.GetObject("fuerza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gestion_cuentas {
            get {
                object obj = ResourceManager.GetObject("gestion_cuentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;HECHIZOS&gt;
        ///  &lt;HECHIZO ID=&quot;1&quot;&gt;
        ///    &lt;NOMBRE&gt;Armadura Incandescente&lt;/NOMBRE&gt;
        ///    &lt;NIVEL NIVEL=&quot;1&quot; COSTE_PA=&quot;2&quot; RANGO_MINIMO=&quot;0&quot; RANGO_MAXIMO=&quot;0&quot; LANZ_EN_LINEA=&quot;FALSE&quot; NECESITA_VISION=&quot;FALSE&quot; NECESITA_CELDA_LIBRE=&quot;FALSE&quot; RANGO_MODIFICABLE=&quot;FALSE&quot; MAX_LANZ_POR_TURNO=&quot;0&quot; MAX_LANZ_POR_OBJETIVO=&quot;0&quot; COOLDOWN=&quot;5&quot;&gt;
        ///      &lt;EFECTO TIPO=&quot;265&quot; COOLDOWN=&quot;4&quot; OBJETIVO=&quot;-1&quot; ZONA=&quot;Cc&quot; ES_CRITICO=&quot;FALSE&quot; /&gt;
        ///      &lt;EFECTO TIPO=&quot;265&quot; COOLDOWN=&quot;4&quot; OBJETIVO=&quot;-1&quot; ZONA=&quot;Cc&quot; ES_CRITICO=&quot;TRU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hechizos {
            get {
                return ResourceManager.GetString("hechizos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icono_escoba {
            get {
                object obj = ResourceManager.GetObject("icono_escoba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap informacion {
            get {
                object obj = ResourceManager.GetObject("informacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iniciativa {
            get {
                object obj = ResourceManager.GetObject("iniciativa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inteligencia {
            get {
                object obj = ResourceManager.GetObject("inteligencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SKILLS&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Alambique&lt;/nombre&gt;
        ///    &lt;gfx&gt;7019&lt;/gfx&gt;
        ///    &lt;caminable&gt;false&lt;/caminable&gt;
        ///    &lt;habilidades&gt;23&lt;/habilidades&gt;
        ///    &lt;recolectable&gt;false&lt;/recolectable&gt;
        ///  &lt;/SKILL&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Arce&lt;/nombre&gt;
        ///    &lt;gfx&gt;7504&lt;/gfx&gt;
        ///    &lt;caminable&gt;false&lt;/caminable&gt;
        ///    &lt;habilidades&gt;37&lt;/habilidades&gt;
        ///    &lt;recolectable&gt;true&lt;/recolectable&gt;
        ///  &lt;/SKILL&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Arroz&lt;/nombre&gt;
        ///    &lt;gfx&gt;7550&lt;/gfx&gt;
        ///    &lt;caminable&gt;true&lt;/caminable&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string interactivos {
            get {
                return ResourceManager.GetString("interactivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invocaciones {
            get {
                object obj = ResourceManager.GetObject("invocaciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lista_cuentas {
            get {
                object obj = ResourceManager.GetObject("lista_cuentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OFICIOS&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;1&lt;/id&gt;
        ///		&lt;nombre&gt;Base&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;2&lt;/id&gt;
        ///		&lt;nombre&gt;Leñador&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;11&lt;/id&gt;
        ///		&lt;nombre&gt;Forjador de espadas&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;13&lt;/id&gt;
        ///		&lt;nombre&gt;Escultor de arcos&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;14&lt;/id&gt;
        ///		&lt;nombre&gt;Forjador de martillos&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;15&lt;/id&gt;
        ///		&lt;nombre&gt;Zapatero&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;16&lt;/id&gt;
        ///		&lt;nomb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oficios {
            get {
                return ResourceManager.GetString("oficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PA {
            get {
                object obj = ResourceManager.GetObject("PA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perfil_default {
            get {
                object obj = ResourceManager.GetObject("perfil_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pm {
            get {
                object obj = ResourceManager.GetObject("pm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prospeccion {
            get {
                object obj = ResourceManager.GetObject("prospeccion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sabiduria {
            get {
                object obj = ResourceManager.GetObject("sabiduria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap suerte {
            get {
                object obj = ResourceManager.GetObject("suerte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap terminal {
            get {
                object obj = ResourceManager.GetObject("terminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vitalidad {
            get {
                object obj = ResourceManager.GetObject("vitalidad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
